data_types:
    input_chunk_length: "int"
    output_chunk_length: "int"
    n_epochs: "int"
    lstm_layers: "int"
    dropout: "float"
    num_attention_heads: "int"
    hidden_size: "int"
    batch_size: "int"
    add_relative_index: "bool"
    optimizer_kwargs: "ast.literal_eval"
    lags_past_covariates: "int"
    lags_future_covariates: "ast.literal_eval"
    lags: "int"
    early_stopping_rounds: "int"
    max_depth: "int"
    min_child_weight: "int"
    gamma: "int"
    colsample_bytree: "float"
    n_estimators: "int"
    learning_rate: "float"
    hidden_dim: "int"
    n_rnn_layers: "int"
    model: "str"
    multi_models: "bool"
    kernel_size: "int"
    trend: "str"
    start_p: "int"
    max_p: "int"
    start_q: "int"
    max_q: "int"
    seasonal: "bool"